#pragma once

#define INVALID_ARG_NUMBER 1
#define CANNOT_START_WSA 2
#define CANNOT_CREATE_SOCKET 3
#define INVALID_IP_ADDR_FORMAT 4
#define SOCKET_BIND_FAIL 5
#define CANNOT_GET_HOSTNAME 6
#define CANNOT_GET_HOST_BY_NAME 7
#define CANNOT_INIT_MAX_CLIENTS_EVENT 8